language: node_js
node_js:
  - "stable"
before_install: cd backend/
install:
  - npm install
script:
  - npm test
  - npm run cover
after_success:
  - npm run coveralls
  - ./node_modules/.bin/mocha

