language: node_js
node_js:
  - "stable"
before_install: cd backend/
install:
  - npm install
script:
  - npm test
after_success:
  - npm run cover
  - npm run coveralls
  # - npm run report-coverage
  - ./node_modules/.bin/mocha
cache:
  directories:
    - backend/node_modules

